<?php /** @var Selfd515\TestCase\Block\Add $block */ ?>
<div style="width: 20vw;">
    <h1>Add new task</h1>
    <h2>Enter taskname:</h2>
    <form action="<?php echo $block->getFormAction() ?>" method="post" data-mage-init='{"validation":{}}'>
            <input name="taskcontent" type="text" data-validate="{required:true, 'validate-no-empty':true}">
            <br /><br />
            <button type="submit" title="Add new task">
                <span>Add new task</span>
            </button>
    </form>
</div>
